### ISSUE TITLE
error: webuntis.0 (6754)

### ISSUE THREAD

**Issue by webmaik** [Newan/ioBroker.webuntis#9]
Hallo,
ich bin sehr an diesem Adapter interessiert, allerdings bekomme ich eineFehlermeldung beim Starten der Instanz.
Gibt es dazu ggf. einen Workaround oder mache ich etwas falsch?

Das sind die Logeintragungen:

2022-03-21 16:33:46.689 - info: webuntis.0 (6754) starting. Version 0.3.2 (non-npm: Newan/ioBroker.webuntis) in /opt/iobroker/node_modules/iobroker.webuntis, node: v12.22.6, js-controller: 4.0.21
--
2022-03-21 16:33:47.518 - error: webuntis.0 (6754) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-03-21 16:33:47.519 - error: webuntis.0 (6754) unhandled promise rejection: Server didn't returned any result.
2022-03-21 16:33:47.521 - error: webuntis.0 (6754) Error: Server didn't returned any result.
at WebUntis._request (/opt/iobroker/node_modules/webuntis/index.js:643:42)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async WebUntis.getOwnTimetableForToday (/opt/iobroker/node_modules/webuntis/index.js:300:16)
2022-03-21 16:33:47.521 - error: webuntis.0 (6754) Server didn't returned any result.
2022-03-21 16:33:47.532 - info: webuntis.0 (6754) terminating
2022-03-21 16:33:47.534 - warn: webuntis.0 (6754) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-03-21 16:33:48.041 - error: webuntis.0 (6754) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-03-21 16:33:48.042 - error: webuntis.0 (6754) unhandled promise rejection: DB closed
2022-03-21 16:33:48.043 - error: webuntis.0 (6754) Error: DB closed
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (events.js:421:26)
at Socket.emit (events.js:314:20)
at TCP. (net.js:675:12)
2022-03-21 16:33:48.044 - error: webuntis.0 (6754) DB closed
2022-03-21 16:33:48.197 - error: host.raspberrypi instance system.adapter.webuntis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

Besten Dank!
Maik

**Comment by Newan** [comment]
Scheinbar unterstützt dien Schule die Funktion nicht:
error: webuntis.0 (6754) Server didn't returned any result. 

WEnn ich mir das ansehen kann, benötige ich die Daten /Login einmal. Gerne auf meine Email

**Comment by webmaik** [comment]
Hallo ,
vielen Dank für die Hilfe 😊

***@***.***
Kennwort ist: Starlight*99

Beste Grüße
Maik

--------------------------------------------------------------------------------------------------------------------------------------
Am Holderbusch 10
D-30657 Hannover

Telefon 0172 4422029
E-Mail ***@***.******@***.***>
Web www.bruenjes.net<http://www.bruenjes.net/>

--------------------------------------------------------------------------------------------------------------------------------------
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist nicht gestattet.
--------------------------------------------------------------------------------------------------------------------------------------

Von: Newan ***@***.***>
Gesendet: Montag, 21. März 2022 16:44
An: Newan/ioBroker.webuntis ***@***.***>
Cc: Maik Brünjes ***@***.***>; Author ***@***.***>
Betreff: Re: [Newan/ioBroker.webuntis] error: webuntis.0 (6754) (Issue #9)


Scheinbar unterstützt dien Schule die Funktion nicht:
error: webuntis.0 (6754) Server didn't returned any result.

WEnn ich mir das ansehen kann, benötige ich die Daten /Login einmal. Gerne auf meine Email

**Comment by Newan** [comment]
bitte an info@newan.de, so kommt das nicht an.

**Comment by Newan** [comment]
Fehler wurde abgefangen in 0.3.3
Hier muss die Schule sich bei Webuntis melden meiner Meinung nach

**Comment by webmaik** [comment]
Vielen Dank :-)
